Final project
AlexJudin/go_final_project pull request #1
Opened 2024-07-20 22:51 UTC by AlexJudin

2024-07-29 12:25 UTC, dirtymew requested changes
Привет Алекс

отличная работа

хочется отметить:
 - документацию(readme, go docs , swagger)
 - логгирование
 - лайаут и архитектуру решения
 - в целом неплохой код
 

есть что немного подправить см PR

2024-07-29 12:25 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
лучше go mod download

2024-07-29 12:25 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
и лучше собрать бинарник и его запускать

а можно еще лучше - сделать https://docs.docker.com/build/building/multi-stage/ 

так можно собрать образ только с одним бинариком - без кода и других артефактов(только про фронт нужно не забыть)

2024-07-29 12:25 UTC, dirtymew commented on api/handler.go
> +	w.Write(messageJson)
_ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-07-29 12:25 UTC, dirtymew commented on .github/workflows/go.yml
>        run: go build -v ./...
ок - но есть вопрос - зачем?

ну action соберет бинарник - а что потом?

2024-07-29 12:25 UTC, dirtymew commented on api/handler.go
> +	nowTime, err := time.Parse("20060102", now)
20060102 - много где используется стоит в константу вынести

2024-07-29 12:25 UTC, dirtymew commented on cmd/main.go
> +	serverAddress := fmt.Sprintf("localhost:%s", cfg.Port)
круто что добавил логирование - стоит им везде и пользоваться, для единообразия

а то где-то logrus где-то fmt

2024-07-29 12:25 UTC, dirtymew commented on compose.yaml
> +      - "7540:7540"
а если TODO_PORT -поменяется?

2024-07-29 12:25 UTC, dirtymew commented on cmd/main.go
> +	logLevel, _ := log.ParseLevel(cfg.LogLevel)
мб эту провеку делать при инициализации конфига лучше

2024-07-29 12:25 UTC, dirtymew commented on repository/sql.go
> +	    title   TEXT NOT NULL DEFAULT "",
title тоже стоит ограничить - но к сожалению  в sqlite это не работает... можно check повесить

2024-07-29 12:25 UTC, dirtymew commented on repository/sql.go
> +	SQLGetTasks = `SELECT * FROM scheduler WHERE date >= $1`
охх лучше всетаки по месту запросы писать - так будет проще понимать что происходит....

2024-07-29 12:25 UTC, dirtymew commented on repository/task.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-07-29 12:25 UTC, dirtymew commented on repository/sql.go
> +	SQLGetTasksByDate = `SELECT * FROM scheduler WHERE date = $1`
лучше явно указать поля чем *

2024-07-29 12:25 UTC, dirtymew commented on repository/sql.go
> +	SQLGetTasksBySearchString = `SELECT * FROM scheduler WHERE title LIKE $1 OR comment LIKE $1 ORDER BY date`
про лимит забыл

2024-07-29 12:25 UTC, dirtymew commented on tests/app_1_test.go
> +	t.Skip()
а это почему? тест должен работать

2024-07-29 12:25 UTC, dirtymew commented on usecases/type.go
> +package usecases
лучше положить интерфес или к реализации или рядом с типо Task

2024-07-29 14:16 UTC, AlexJudin commented on cmd/main.go
> +	serverAddress := fmt.Sprintf("localhost:%s", cfg.Port)
исправил

2024-07-29 14:17 UTC, AlexJudin commented on tests/app_1_test.go
> +	t.Skip()
исправил

2024-07-29 14:21 UTC, AlexJudin commented on repository/task.go
> +
исправил

2024-07-29 14:31 UTC, AlexJudin commented on api/handler.go
> +	w.Write(messageJson)
исправил

2024-07-29 14:46 UTC, AlexJudin commented on .github/workflows/go.yml
>        run: go build -v ./...
оставил только литеры

2024-07-29 14:58 UTC, AlexJudin commented on api/handler.go
> +	nowTime, err := time.Parse("20060102", now)
для своего кода исправил. тесты не стал трогать.

2024-07-29 15:04 UTC, AlexJudin commented on repository/sql.go
> +	SQLGetTasksByDate = `SELECT * FROM scheduler WHERE date = $1`
исправил

2024-07-29 16:08 UTC, AlexJudin commented on usecases/type.go
> +package usecases
интерфейс Task из этого пакета описывает тип TaskUsecase. Директорию model вынес в корень, в ней общие для для всех слоев объекты.

2024-07-29 16:39 UTC, AlexJudin commented on repository/sql.go
> +	SQLGetTasksBySearchString = `SELECT * FROM scheduler WHERE title LIKE $1 OR comment LIKE $1 ORDER BY date`
исправил

2024-07-29 17:29 UTC, AlexJudin commented on Dockerfile
> +RUN go mod tidy
исправил

2024-07-30 09:38 UTC, AlexJudin commented on compose.yaml
> +      - "7540:7540"
этот файл убрал

2024-07-30 15:05 UTC, AlexJudin commented on cmd/main.go
> +	logLevel, _ := log.ParseLevel(cfg.LogLevel)
Исправил

2024-07-30 15:11 UTC, dirtymew requested changes
Привет Алекс

все супер - тесты проходят

осталось разобраться с фронтом - не смог залогиниться черещ него

2024-07-30 15:11 UTC, dirtymew commented on middleware/auth.go
> +func (a *AuthMW) Auth(next http.HandlerFunc) http.HandlerFunc {
Не смог проверить работу системы с front-а  при вводе пароля

<img width="589" alt="image" src="https://github.com/user-attachments/assets/50999200-92e2-46aa-9e32-9d8b901daf7b">

2024-07-30 15:12 UTC, AlexJudin commented on repository/sql.go
> +	SQLGetTasks = `SELECT * FROM scheduler WHERE date >= $1`
исправил

2024-07-30 15:17 UTC, AlexJudin commented on repository/sql.go
> +	    title   TEXT NOT NULL DEFAULT "",
исправил

2024-07-30 15:28 UTC, AlexJudin commented on middleware/auth.go
> +func (a *AuthMW) Auth(next http.HandlerFunc) http.HandlerFunc {
Исправил

2024-07-30 16:14 UTC, dirtymew approved these changes
Привет

все отлично - супер крутая работа, конечно нет приделов совершенству, совет  - по аккуратнее с кол-вом абстракций ))

Поздравляю и желаю удачи

2024-07-30 16:14 UTC, dirtymew commented on compose.yaml
> +    command: go run cmd/main.go
у тебя уже же есть сборка - так и запускай бинарник /alexeyjudin а не через go )

2024-07-30 19:03 UTC, AlexJudin commented on compose.yaml
> +    command: go run cmd/main.go
Убрал)

2024-07-30 19:56 UTC, merged